organization: zaibonstor                                # itsyou.online organization name
namespace: thedisk                                  # itsyou.online namespace
protocol: grpc
iyo_app_id: KkF4sr2RYxquXY6eZ5m1kbsGSmRQ
iyo_app_secret: fGTtw6XpagL13fVjNpIoA_JZZuAK

shards:                                             # the address(es) of 0-stor server
    - 127.0.0.1:12345
    - 127.0.0.1:12346
    - 127.0.0.1:12347
meta_shards:
    - http://127.0.0.1:23790                         # the address(es) of etcd server

pipes:
    - name: pipe0
      type: chunker
      config:
          chunkSize: 1024000

    - name: pipe1
      type: compress
      config:
          type: snappy

    - name: pipe2
      type: encrypt
      config:
          type: aes_gcm
          privKey: ab345678901234567890123456789012

    - name: pipe3
      type: distribution
      config:
          data: 2
          parity: 1

