# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import proxy_pb2 as proxy__pb2


class NamespaceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateJWT = channel.unary_unary(
        '/proxy.NamespaceService/CreateJWT',
        request_serializer=proxy__pb2.CreateJWTRequest.SerializeToString,
        response_deserializer=proxy__pb2.CreateJWTReply.FromString,
        )
    self.CreateNamespace = channel.unary_unary(
        '/proxy.NamespaceService/CreateNamespace',
        request_serializer=proxy__pb2.NamespaceRequest.SerializeToString,
        response_deserializer=proxy__pb2.NamespaceReply.FromString,
        )
    self.DeleteNamespace = channel.unary_unary(
        '/proxy.NamespaceService/DeleteNamespace',
        request_serializer=proxy__pb2.NamespaceRequest.SerializeToString,
        response_deserializer=proxy__pb2.NamespaceReply.FromString,
        )
    self.GivePermission = channel.unary_unary(
        '/proxy.NamespaceService/GivePermission',
        request_serializer=proxy__pb2.EditPermissionRequest.SerializeToString,
        response_deserializer=proxy__pb2.EditPermissionReply.FromString,
        )
    self.RemovePermission = channel.unary_unary(
        '/proxy.NamespaceService/RemovePermission',
        request_serializer=proxy__pb2.EditPermissionRequest.SerializeToString,
        response_deserializer=proxy__pb2.EditPermissionReply.FromString,
        )
    self.GetPermission = channel.unary_unary(
        '/proxy.NamespaceService/GetPermission',
        request_serializer=proxy__pb2.GetPermissionRequest.SerializeToString,
        response_deserializer=proxy__pb2.GetPermissionReply.FromString,
        )


class NamespaceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateJWT(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateNamespace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNamespace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GivePermission(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemovePermission(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPermission(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NamespaceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateJWT': grpc.unary_unary_rpc_method_handler(
          servicer.CreateJWT,
          request_deserializer=proxy__pb2.CreateJWTRequest.FromString,
          response_serializer=proxy__pb2.CreateJWTReply.SerializeToString,
      ),
      'CreateNamespace': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNamespace,
          request_deserializer=proxy__pb2.NamespaceRequest.FromString,
          response_serializer=proxy__pb2.NamespaceReply.SerializeToString,
      ),
      'DeleteNamespace': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNamespace,
          request_deserializer=proxy__pb2.NamespaceRequest.FromString,
          response_serializer=proxy__pb2.NamespaceReply.SerializeToString,
      ),
      'GivePermission': grpc.unary_unary_rpc_method_handler(
          servicer.GivePermission,
          request_deserializer=proxy__pb2.EditPermissionRequest.FromString,
          response_serializer=proxy__pb2.EditPermissionReply.SerializeToString,
      ),
      'RemovePermission': grpc.unary_unary_rpc_method_handler(
          servicer.RemovePermission,
          request_deserializer=proxy__pb2.EditPermissionRequest.FromString,
          response_serializer=proxy__pb2.EditPermissionReply.SerializeToString,
      ),
      'GetPermission': grpc.unary_unary_rpc_method_handler(
          servicer.GetPermission,
          request_deserializer=proxy__pb2.GetPermissionRequest.FromString,
          response_serializer=proxy__pb2.GetPermissionReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proxy.NamespaceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ObjectServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Write = channel.unary_unary(
        '/proxy.ObjectService/Write',
        request_serializer=proxy__pb2.WriteRequest.SerializeToString,
        response_deserializer=proxy__pb2.WriteReply.FromString,
        )
    self.WriteFile = channel.unary_unary(
        '/proxy.ObjectService/WriteFile',
        request_serializer=proxy__pb2.WriteFileRequest.SerializeToString,
        response_deserializer=proxy__pb2.WriteFileReply.FromString,
        )
    self.WriteStream = channel.stream_unary(
        '/proxy.ObjectService/WriteStream',
        request_serializer=proxy__pb2.WriteStreamRequest.SerializeToString,
        response_deserializer=proxy__pb2.WriteStreamReply.FromString,
        )
    self.Read = channel.unary_unary(
        '/proxy.ObjectService/Read',
        request_serializer=proxy__pb2.ReadRequest.SerializeToString,
        response_deserializer=proxy__pb2.ReadReply.FromString,
        )
    self.ReadFile = channel.unary_unary(
        '/proxy.ObjectService/ReadFile',
        request_serializer=proxy__pb2.ReadFileRequest.SerializeToString,
        response_deserializer=proxy__pb2.ReadFileReply.FromString,
        )
    self.ReadStream = channel.unary_stream(
        '/proxy.ObjectService/ReadStream',
        request_serializer=proxy__pb2.ReadRequest.SerializeToString,
        response_deserializer=proxy__pb2.ReadReply.FromString,
        )
    self.Delete = channel.unary_unary(
        '/proxy.ObjectService/Delete',
        request_serializer=proxy__pb2.DeleteRequest.SerializeToString,
        response_deserializer=proxy__pb2.NullReply.FromString,
        )
    self.Walk = channel.unary_stream(
        '/proxy.ObjectService/Walk',
        request_serializer=proxy__pb2.WalkRequest.SerializeToString,
        response_deserializer=proxy__pb2.WalkReply.FromString,
        )
    self.AppendReferenceList = channel.unary_unary(
        '/proxy.ObjectService/AppendReferenceList',
        request_serializer=proxy__pb2.ReferenceListRequest.SerializeToString,
        response_deserializer=proxy__pb2.NullReply.FromString,
        )
    self.RemoveReferenceList = channel.unary_unary(
        '/proxy.ObjectService/RemoveReferenceList',
        request_serializer=proxy__pb2.ReferenceListRequest.SerializeToString,
        response_deserializer=proxy__pb2.NullReply.FromString,
        )
    self.Check = channel.unary_unary(
        '/proxy.ObjectService/Check',
        request_serializer=proxy__pb2.CheckRequest.SerializeToString,
        response_deserializer=proxy__pb2.CheckReply.FromString,
        )
    self.Repair = channel.unary_unary(
        '/proxy.ObjectService/Repair',
        request_serializer=proxy__pb2.RepairRequest.SerializeToString,
        response_deserializer=proxy__pb2.NullReply.FromString,
        )


class ObjectServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Write(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Walk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendReferenceList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveReferenceList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Repair(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=proxy__pb2.WriteRequest.FromString,
          response_serializer=proxy__pb2.WriteReply.SerializeToString,
      ),
      'WriteFile': grpc.unary_unary_rpc_method_handler(
          servicer.WriteFile,
          request_deserializer=proxy__pb2.WriteFileRequest.FromString,
          response_serializer=proxy__pb2.WriteFileReply.SerializeToString,
      ),
      'WriteStream': grpc.stream_unary_rpc_method_handler(
          servicer.WriteStream,
          request_deserializer=proxy__pb2.WriteStreamRequest.FromString,
          response_serializer=proxy__pb2.WriteStreamReply.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=proxy__pb2.ReadRequest.FromString,
          response_serializer=proxy__pb2.ReadReply.SerializeToString,
      ),
      'ReadFile': grpc.unary_unary_rpc_method_handler(
          servicer.ReadFile,
          request_deserializer=proxy__pb2.ReadFileRequest.FromString,
          response_serializer=proxy__pb2.ReadFileReply.SerializeToString,
      ),
      'ReadStream': grpc.unary_stream_rpc_method_handler(
          servicer.ReadStream,
          request_deserializer=proxy__pb2.ReadRequest.FromString,
          response_serializer=proxy__pb2.ReadReply.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=proxy__pb2.DeleteRequest.FromString,
          response_serializer=proxy__pb2.NullReply.SerializeToString,
      ),
      'Walk': grpc.unary_stream_rpc_method_handler(
          servicer.Walk,
          request_deserializer=proxy__pb2.WalkRequest.FromString,
          response_serializer=proxy__pb2.WalkReply.SerializeToString,
      ),
      'AppendReferenceList': grpc.unary_unary_rpc_method_handler(
          servicer.AppendReferenceList,
          request_deserializer=proxy__pb2.ReferenceListRequest.FromString,
          response_serializer=proxy__pb2.NullReply.SerializeToString,
      ),
      'RemoveReferenceList': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveReferenceList,
          request_deserializer=proxy__pb2.ReferenceListRequest.FromString,
          response_serializer=proxy__pb2.NullReply.SerializeToString,
      ),
      'Check': grpc.unary_unary_rpc_method_handler(
          servicer.Check,
          request_deserializer=proxy__pb2.CheckRequest.FromString,
          response_serializer=proxy__pb2.CheckReply.SerializeToString,
      ),
      'Repair': grpc.unary_unary_rpc_method_handler(
          servicer.Repair,
          request_deserializer=proxy__pb2.RepairRequest.FromString,
          response_serializer=proxy__pb2.NullReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proxy.ObjectService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
