coverage:
  range: 50..70
  round: down
  precision: 0
  ignore:
    # ignore all generated files, as we do not control those
    - server/api/grpc/schema/zstor.pb.go
    - server/api/grp/generate.go
    - client/metastor/encoding/proto/generate.go
    - client/metastor/encoding/proto/metadata.pb.go
