organization: mordor                                # itsyou.online organization name
namespace: thedisk                                  # itsyou.online namespace
meta_shards:
    - http://127.0.0.1:2379                         # the address(es) of etcd server
pipes:
    - name: pipe1
      type: compress
      config:
          type: snappy

    - name: pipe2
      type: encrypt 
      config:
          type: aes_gcm
          privKey: ab345678901234567890123456789012
          nonce: 123456789012


    - name: pipe3
      type: distribution
      config:
          protocol: rest
          data: 1
          parity: 1
          shards:                                             # the address(es) of 0-stor server
            - http://127.0.0.1:8080
            - http://127.0.0.1:8081
          stor_perm_write: true
          stor_perm_read: true
          iyo_client_id: abcde                      # itsyou.online client iD
          iyo_secret: abcde                          # itsyou.online client secret

    - name: pipe4
      type: meta 
      config:
          shards:
              - http://127.0.0.1:2379

