datastor:
  shards:
  - 127.0.0.1:12345
  - 127.0.0.1:12346
  - 127.0.0.1:12347

    #iyo:
#  app_id: <iyo appid>
# app_secret: <iyo secret>
#organization: <iyo org>

metastor:
  db:
    endpoints:
    - 127.0.0.1:2379
    - 127.0.0.1:22379
    - 127.0.0.1:32379

namespace: test
pipeline:
  block_size: 4096
  compression:
    mode: default
    type: snappy
  distribution:
    data_shards: 1
    parity_shards: 1
